version: '3.9'
services:
  web:

    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
    - "8000:8000"

    volumes:
    - type: bind
      source: ../
      target: /sonny_andi_pdf 

  test:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
    - type: bind
      source: ../
      target: /sonny_andi_pdf

    command: /bin/bash

